<?php
// app/Http/Controllers/UpdateController.php
namespace App\Http\Controllers;

use Illuminate\Support\Facades\Artisan;
use Illuminate\Http\Request;

class UpdateController extends Controller
{
    public function update(Request $request)
    {
        // Run the custom artisan command
        Artisan::call('app:update');

        // Get all output generated by $this->info(), $this->error() etc.
        $output = Artisan::output();

        // Simple status detection
        $status = str_contains($output, 'Update complete') ? 'success' : 'failed';

        return response()->json([
            'status' => $status,
            'output' => nl2br(e($output)), // keep line breaks
        ]);
    }
}

